# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import adaptive_pb2 as adaptive__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in adaptive_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CodecServiceStub(object):
    """#region service-definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Generate = channel.unary_unary(
                '/adaptive.CodecService/Generate',
                request_serializer=adaptive__pb2.GenerateRequest.SerializeToString,
                response_deserializer=adaptive__pb2.GenerateResponse.FromString,
                _registered_method=True)
        self.Embed = channel.unary_unary(
                '/adaptive.CodecService/Embed',
                request_serializer=adaptive__pb2.EmbedRequest.SerializeToString,
                response_deserializer=adaptive__pb2.EmbedResponse.FromString,
                _registered_method=True)
        self.Search = channel.unary_unary(
                '/adaptive.CodecService/Search',
                request_serializer=adaptive__pb2.SearchRequest.SerializeToString,
                response_deserializer=adaptive__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.StoreEvidence = channel.unary_unary(
                '/adaptive.CodecService/StoreEvidence',
                request_serializer=adaptive__pb2.StoreEvidenceRequest.SerializeToString,
                response_deserializer=adaptive__pb2.StoreEvidenceResponse.FromString,
                _registered_method=True)
        self.WebSearch = channel.unary_unary(
                '/adaptive.CodecService/WebSearch',
                request_serializer=adaptive__pb2.WebSearchRequest.SerializeToString,
                response_deserializer=adaptive__pb2.WebSearchResponse.FromString,
                _registered_method=True)
        self.DeleteEvidence = channel.unary_unary(
                '/adaptive.CodecService/DeleteEvidence',
                request_serializer=adaptive__pb2.DeleteEvidenceRequest.SerializeToString,
                response_deserializer=adaptive__pb2.DeleteEvidenceResponse.FromString,
                _registered_method=True)


class CodecServiceServicer(object):
    """#region service-definition
    """

    def Generate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Embed(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StoreEvidence(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WebSearch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteEvidence(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CodecServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Generate': grpc.unary_unary_rpc_method_handler(
                    servicer.Generate,
                    request_deserializer=adaptive__pb2.GenerateRequest.FromString,
                    response_serializer=adaptive__pb2.GenerateResponse.SerializeToString,
            ),
            'Embed': grpc.unary_unary_rpc_method_handler(
                    servicer.Embed,
                    request_deserializer=adaptive__pb2.EmbedRequest.FromString,
                    response_serializer=adaptive__pb2.EmbedResponse.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=adaptive__pb2.SearchRequest.FromString,
                    response_serializer=adaptive__pb2.SearchResponse.SerializeToString,
            ),
            'StoreEvidence': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreEvidence,
                    request_deserializer=adaptive__pb2.StoreEvidenceRequest.FromString,
                    response_serializer=adaptive__pb2.StoreEvidenceResponse.SerializeToString,
            ),
            'WebSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.WebSearch,
                    request_deserializer=adaptive__pb2.WebSearchRequest.FromString,
                    response_serializer=adaptive__pb2.WebSearchResponse.SerializeToString,
            ),
            'DeleteEvidence': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteEvidence,
                    request_deserializer=adaptive__pb2.DeleteEvidenceRequest.FromString,
                    response_serializer=adaptive__pb2.DeleteEvidenceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'adaptive.CodecService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('adaptive.CodecService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CodecService(object):
    """#region service-definition
    """

    @staticmethod
    def Generate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/adaptive.CodecService/Generate',
            adaptive__pb2.GenerateRequest.SerializeToString,
            adaptive__pb2.GenerateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Embed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/adaptive.CodecService/Embed',
            adaptive__pb2.EmbedRequest.SerializeToString,
            adaptive__pb2.EmbedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/adaptive.CodecService/Search',
            adaptive__pb2.SearchRequest.SerializeToString,
            adaptive__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StoreEvidence(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/adaptive.CodecService/StoreEvidence',
            adaptive__pb2.StoreEvidenceRequest.SerializeToString,
            adaptive__pb2.StoreEvidenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WebSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/adaptive.CodecService/WebSearch',
            adaptive__pb2.WebSearchRequest.SerializeToString,
            adaptive__pb2.WebSearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteEvidence(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/adaptive.CodecService/DeleteEvidence',
            adaptive__pb2.DeleteEvidenceRequest.SerializeToString,
            adaptive__pb2.DeleteEvidenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
